export const CREATE_WALLET = "CREATE_WALLET";
export const CREATE_WALLET_ERROR = "CREATE_WALLET_ERROR";
export const CREATE_WALLET_SUCCESS = "CREATE_WALLET_SUCCESS";

export const FETCH_WALLET = "FETCH_WALLET";
export const FETCH_WALLET_ERROR = "FETCH_WALLET_ERROR";
export const FETCH_WALLET_SUCCESS = "FETCH_WALLET_SUCCESS";
