import React from 'react'
import { IoIosMail } from 'react-icons/io'
import { SiAuthelia } from 'react-icons/si'

function TwoFactorAuthentication() {
  return (
    <div>
                <div className="my-5 rounded-md border border-gray-400 bg-white p-4 px-8">
                  <div className=" mb-8">
                    <h2 className=" text-[#29A744] text-2xl">
                      Two-factor authentication (2FA) settings
                    </h2>
                  </div>

                  <div className=" mb-5">
                    <p>Set up your 2FA and make your account more secure.</p>
                  </div>

                  <div className=" grid lg:grid-cols-2 grid-cols-1 gap-y-10 gap-[10%]">
                    <div className=" flex items-center justify-between  ">
                      <div className=" flex gap-4 items-center ">
                        <SiAuthelia className=" text-[#29A744] text-5xl" />

                        <div className=" flex flex-col gap-1">
                          <h3 className=" text-xl">
                            Google Authenticator or Authy
                          </h3>
                          <p className=" text-gray-500">
                            Random time-bound passcode generated by the app.
                          </p>
                        </div>
                      </div>
                      <div>
                        <button className=" text-[#29A744]">
                          Activate Now
                        </button>
                      </div>
                    </div>
                    <div className=" flex items-center justify-between  ">
                      <div className=" flex gap-4 items-center ">
                        <IoIosMail className=" text-[#29A744] text-5xl" />
                        <div className=" flex flex-col gap-1">
                          <h3 className=" text-xl">Email</h3>
                          <p className=" text-gray-500">
                            A unique time-bound code sent via email.
                          </p>
                        </div>
                      </div>
                      <div>
                        <button className=" text-[#29A744]">
                          Activate Now
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
  )
}

export default TwoFactorAuthentication