// trade
export const START_TRADE = "START_TRADE";
export const START_TRADE_SUCCESS = "START_TRADE_SUCCESS";
export const START_TRADE_ERROR = "START_TRADE_ERROR";

export const ENGAGE_USER = "ENGAGE_USER";
export const ENGAGE_USER_SUCCESS = "ENGAGE_USER_SUCCESS";
export const ENGAGE_USER_ERROR = "ENGAGE_USER_ERROR";

export const FETCH_TRADES_LIST = "FETCH_TRADES_LIST";
export const FETCH_TRADES_LIST_SUCCESS = "FETCH_TRADES_LIST_SUCCESS";
export const FETCH_TRADES_LIST_ERROR = "FETCH_TRADES_LIST_ERROR";

export const FETCH_TRADE_BY_ID = "FETCH_TRADE_BY_ID";
export const FETCH_TRADE_BY_ID_SUCCESS = "FETCH_TRADE_BY_ID_SUCCESS";
export const FETCH_TRADE_BY_ID_ERROR = "FETCH_TRADE_BY_ID_ERROR";

export const CANCEL_TRADE = "CANCEL_TRADE";
export const CANCEL_TRADE_SUCCESS = "CANCEL_TRADE_SUCCESS";
export const CANCEL_TRADE_ERROR = "CANCEL_TRADE_ERROR";

export const COMPLETE_TRADE = "COMPLETE_TRADE";
export const COMPLETE_TRADE_SUCCESS = "COMPLETE_TRADE_SUCCESS";
export const COMPLETE_TRADE_ERROR = "COMPLETE_TRADE_ERROR";

export const UPDATE_TRADE_STATUS = "UPDATE_TRADE";
export const UPDATE_TRADE_STATUS_SUCCESS = "UPDATE_TRADE_SUCCESS";
export const UPDATE_TRADE_STATUS_ERROR = "UPDATE_TRADE_ERROR";
