export const CREATE_IP_INFO = "CREATE_IP_INFO";
export const CREATE_IP_INFO_ERROR = "CREATE_IP_INFO_ERROR";
export const CREATE_IP_INFO_SUCCESS = "CREATE_IP_INFO_SUCCESS";

export const FETCH_IP_INFO = "FETCH_IP_INFO";
export const FETCH_IP_INFO_ERROR = "FETCH_IP_INFO_ERROR";
export const FETCH_IP_INFO_SUCCESS = "FETCH_IP_INFO_SUCCESS";