export const OTP_RESEND = "OTP_RESEND"
export const OTP_RESEND_SUCCESS = "OTP_RESEND_SUCCESS"
export const OTP_RESEND_API_ERROR = "OTP_RESEND_API_ERROR"

export const OTP_VERIFY = "OTP_VERIFY"
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS"
export const OTP_VERIFY_API_ERROR = "OTP_VERIFY_API_ERROR"

