export const CREATE_BIDS = "CREATE_BIDS"
export const CREATE_BIDS_SUCCESS = "CREATE_BIDS_SUCCESS"
export const CREATE_BIDS_API_ERROR = "CREATE_BIDS_API_ERROR"

export const GET_BIDS = "GET_BIDS"
export const GET_BIDS_SUCCESS = "GET_BIDS_SUCCESS"
export const GET_BIDS_API_ERROR = "GET_BIDS_API_ERROR"